#!/usr/bin/env bash
set -euo pipefail

# List all generated RTSP URIs for nvs_rtsp_server.
# Default behavior:
# - Read runtime settings from /etc/default/nvs_rtsp_server
# - Read stream map from /usr/local/etc/nvs_rtsp_server/stream_map.tsv
# - Detect IPv4 address from eth0
# - Print one RTSP URI per line
#
# Example:
#   nvs_rtsp_list_uris.sh
#   nvs_rtsp_list_uris.sh --interface eth0
#   nvs_rtsp_list_uris.sh --interface eth0 --show-file

SERVICE_NAME="nvs_rtsp_server"
ENV_FILE="/etc/default/${SERVICE_NAME}"
DEFAULT_STREAM_MAP="/usr/local/etc/${SERVICE_NAME}/stream_map.tsv"
DEFAULT_RTSP_USER="senao"
DEFAULT_RTSP_PASS="admin123"
DEFAULT_RTSP_PORT="8559"
DEFAULT_INTERFACE="eth0"

RTSP_USER="${DEFAULT_RTSP_USER}"
RTSP_PASS="${DEFAULT_RTSP_PASS}"
RTSP_PORT="${DEFAULT_RTSP_PORT}"
STREAM_MAP_FILE="${DEFAULT_STREAM_MAP}"
NET_IFACE="${DEFAULT_INTERFACE}"
SHOW_FILE="no"
SHOW_CHANNEL="no"

usage() {
    cat <<USAGE
Usage:
  ${0##*/} [options]

Options:
  --interface IFACE   Network interface used to detect IPv4 (default: ${DEFAULT_INTERFACE})
  --stream-map FILE   Stream map file path (default: ${DEFAULT_STREAM_MAP})
  --show-file         Append the source mp4 path after each URI
  --show-channel      Prefix each URI with the channel number
  -h, --help          Show this help

Notes:
  * Credentials and port are loaded from ${ENV_FILE} when available.
  * The script expects the stream map format generated by nvs_rtsp_server:
      <channel> <tab> <path> <tab> <file>
USAGE
}

err() {
    echo "[ERROR] $*" >&2
}

load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        RTSP_USER="${RTSP_USER:-$DEFAULT_RTSP_USER}"
        RTSP_PASS="${RTSP_PASS:-$DEFAULT_RTSP_PASS}"
        RTSP_PORT="${RTSP_PORT:-$DEFAULT_RTSP_PORT}"
        STREAM_MAP_FILE="${NVS_STREAM_MAP:-$STREAM_MAP_FILE}"
    fi
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --interface)
                NET_IFACE="${2:-}"
                shift 2
                ;;
            --stream-map)
                STREAM_MAP_FILE="${2:-}"
                shift 2
                ;;
            --show-file)
                SHOW_FILE="yes"
                shift
                ;;
            --show-channel)
                SHOW_CHANNEL="yes"
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                err "unknown argument: $1"
                usage >&2
                exit 1
                ;;
        esac
    done
}

get_ipv4_from_interface() {
    local iface="$1"
    ip -4 -o addr show dev "$iface" scope global 2>/dev/null \
        | awk '{print $4}' \
        | cut -d'/' -f1 \
        | head -n1
}

print_uris() {
    local pi_ip="$1"
    local channel path file uri

    while IFS=$'\t' read -r channel path file; do
        [[ -n "${path:-}" ]] || continue
        uri="rtsp://${RTSP_USER}:${RTSP_PASS}@${pi_ip}:${RTSP_PORT}/${path}"

        if [[ "$SHOW_CHANNEL" == "yes" && "$SHOW_FILE" == "yes" ]]; then
            printf '%s\t%s\t%s\n' "$channel" "$uri" "$file"
        elif [[ "$SHOW_CHANNEL" == "yes" ]]; then
            printf '%s\t%s\n' "$channel" "$uri"
        elif [[ "$SHOW_FILE" == "yes" ]]; then
            printf '%s\t%s\n' "$uri" "$file"
        else
            printf '%s\n' "$uri"
        fi
    done < "$STREAM_MAP_FILE"
}

main() {
    load_env
    parse_args "$@"

    if [[ ! -f "$STREAM_MAP_FILE" ]]; then
        err "stream map file not found: $STREAM_MAP_FILE"
        err "make sure ${SERVICE_NAME}.service has been installed and started"
        exit 1
    fi

    local pi_ip
    pi_ip="$(get_ipv4_from_interface "$NET_IFACE")"
    if [[ -z "$pi_ip" ]]; then
        err "cannot detect IPv4 address from interface: $NET_IFACE"
        exit 1
    fi

    print_uris "$pi_ip"
}

main "$@"
